
import clases.Agente_inmobiliario;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class Administrador_Login extends javax.swing.JFrame {

    
    public static String nombre="",apellido=" ";
    String  password = " ";
    public static String usuario = " ";
    public Administrador_Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        txtcantra = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btninicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtusuario.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtusuario.setBorder(null);
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusuarioMouseClicked(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 226, 226, 50));

        txtcantra.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txtcantra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcantra.setActionCommand("<Not Set>");
        txtcantra.setBorder(null);
        txtcantra.setMinimumSize(new java.awt.Dimension(15, 24));
        txtcantra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcantraMouseClicked(evt);
            }
        });
        txtcantra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantraActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 226, 50));

        btnRegistrar.setBackground(new java.awt.Color(156, 137, 165));
        btnRegistrar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnRegistrar.setText("SOLICITAR CUENTA");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 290, 70));

        btninicio.setBackground(new java.awt.Color(156, 137, 165));
        btninicio.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btninicio.setText("INICIAR SESIÓN");
        btninicio.setBorder(null);
        btninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninicioActionPerformed(evt);
            }
        });
        getContentPane().add(btninicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 290, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninicioActionPerformed

        ObjectContainer base = Db4o.openFile(INICIO.direccion);

        Query query = base.query();
        query.constrain(Agente_inmobiliario.class);
        query.descend("usuario").constrain(txtusuario.getText().trim());
        query.descend("password").constrain(txtcantra.getText().trim());

        ObjectSet<Agente_inmobiliario> result = query.execute();

        if (!result.isEmpty()) {

            for (Agente_inmobiliario agente : result) {
                usuario = agente.getUsuario();
                password = agente.getPassword();
                nombre=agente.getNombre();
                apellido=agente.getApellido();

            }

            this.dispose();
            Menu_agente admin = new Menu_agente();
            admin.setVisible(true);

            txtusuario.setText(usuario.trim());
            txtcantra.setText(password.trim());

        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
        }

        base.close();


    }//GEN-LAST:event_btninicioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        JOptionPane.showMessageDialog(null, "Por favor si necesita una cuenta como Agente Inmobiliario , por favor comunicate primero con el Administrador del Programa", "ERROR", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtcantraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantraActionPerformed

    }//GEN-LAST:event_txtcantraActionPerformed

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped

    }//GEN-LAST:event_txtusuarioKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        INICIO let = new INICIO();
        let.setVisible(true);
        this.dispose();

        setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMouseClicked
        txtusuario.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioMouseClicked

    private void txtcantraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcantraMouseClicked
        txtcantra.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btninicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtcantra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
