
import clases.Agente_inmobiliario;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo.User
 */
public class Ingreso_agente extends javax.swing.JPanel {

    /**
     * Creates new form Ingreso_agente
     */
    /**
     * Creates new form menu_agente
     */
    String sexo;

    public Ingreso_agente() {

        initComponents();
        Agrupar();


        // btnguardar.setEnabled(false);
    }

    public void Agrupar() {
        ButtonGroup botones = new ButtonGroup();
        botones.add(rbnfemenino);
        botones.add(rbnmasculino);

    }

    public void validar() {

        if (txtcedula.getText().trim().isEmpty()) {
            lblced.setText("Campo requerido");

        } else {
            lblced.setText(" ");
        }


        if (txtnombre.getText().isEmpty()) {
            lblnom.setText("Campo requerido");

        } else {
            lblnom.setText(" ");
        }

        if (txtapellido.getText().isEmpty()) {
            lblape.setText("Campo requerido");

        } else {
            lblape.setText(" ");
        }

        if (txttelefono.getText().isEmpty()) {
            lblcelular.setText("Campo requerido");

        } else {
            lblcelular.setText(" ");
        }

        if (jDateChooser1.getDate() == null) {
            lbldate.setText("Campo requerido");

        } else {
            lbldate.setText(" ");
        }

        /*
        if (!rbnfemenino.isSelected() || !rbnmasculino.isSelected()) {
            lblgenero.setText("Campo requerido");

        } else {
            lblgenero.setText(" ");
        }
         */
        if (rbnfemenino.isSelected()) {
            lblgenero.setText(" ");
        } else if (rbnmasculino.isSelected()) {
            lblgenero.setText(" ");

        } else if (!rbnfemenino.isSelected() || !rbnmasculino.isSelected()) {
            lblgenero.setText("Campo requerido");

        }
        if (txtcorreo.getText().isEmpty()) {
            lblcorreo.setText("Campo Obligatoria");
        } else if (!txtcorreo.getText().contains("@") || !txtcorreo.getText().contains(".")) {
            lblcorreo.setText("Correo invalido");
        } else {
            lblcorreo.setText("");
        }

        if ( txtcedula.getText().isEmpty() || (!rbnfemenino.isSelected() && !rbnmasculino.isSelected()) || (!txtcorreo.getText().contains("@") || !txtcorreo.getText().contains(".")) || txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txttelefono.getText().isEmpty() || jDateChooser1.getDate() == null || txtcorreo.getText().isEmpty()) {

            btnguardar.setEnabled(false);
        } else {
            btnguardar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlingreso = new javax.swing.JPanel();
        lbltelefono = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblcedula = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        lblsexo = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        rbnmasculino = new javax.swing.JRadioButton();
        rbnfemenino = new javax.swing.JRadioButton();
        lblemail = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        lbldate = new javax.swing.JLabel();
        lbled = new javax.swing.JLabel();
        lblgenero = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        lblape = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lblcelular = new javax.swing.JLabel();
        lblced = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pnlingreso.setBackground(new java.awt.Color(255, 255, 255));
        pnlingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de agente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 36))); // NOI18N

        lbltelefono.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbltelefono.setText("Teléfono :");

        lblapellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblapellido.setText("Apellido:");

        lblfecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblfecha.setText("Fecha de Nacimiento:");

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        lblcedula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblcedula.setText("Cedula :");

        lblnombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblnombre.setText("Nombre :");

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        lblsexo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblsexo.setText("Sexo :");

        lblcod.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        rbnmasculino.setText("Masculino");
        rbnmasculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbnmasculinoItemStateChanged(evt);
            }
        });
        rbnmasculino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbnmasculinoStateChanged(evt);
            }
        });
        rbnmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnmasculinoActionPerformed(evt);
            }
        });
        rbnmasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbnmasculinoKeyReleased(evt);
            }
        });

        rbnfemenino.setText("Femenino");
        rbnfemenino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbnfemeninoStateChanged(evt);
            }
        });
        rbnfemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnfemeninoActionPerformed(evt);
            }
        });
        rbnfemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbnfemeninoKeyReleased(evt);
            }
        });

        lblemail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblemail.setText("Email:");

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });

        lbldate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldate.setForeground(new java.awt.Color(204, 0, 0));

        lbled.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbled.setForeground(new java.awt.Color(204, 0, 0));

        lblgenero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblgenero.setForeground(new java.awt.Color(204, 0, 0));

        lblnom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnom.setForeground(new java.awt.Color(204, 0, 0));

        lblape.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblape.setForeground(new java.awt.Color(204, 0, 0));

        lblcorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcorreo.setForeground(new java.awt.Color(204, 0, 0));

        lblcelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcelular.setForeground(new java.awt.Color(204, 0, 0));

        lblced.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblced.setForeground(new java.awt.Color(204, 0, 0));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGOS DE KAME HOUSE.PNG"))); // NOI18N

        javax.swing.GroupLayout pnlingresoLayout = new javax.swing.GroupLayout(pnlingreso);
        pnlingreso.setLayout(pnlingresoLayout);
        pnlingresoLayout.setHorizontalGroup(
            pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlingresoLayout.createSequentialGroup()
                .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlingresoLayout.createSequentialGroup()
                                .addComponent(rbnmasculino)
                                .addGap(42, 42, 42)
                                .addComponent(rbnfemenino))
                            .addComponent(lbled, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnom, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblape, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlingresoLayout.createSequentialGroup()
                                .addComponent(lblced, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcod, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblgenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(txtcedula, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlingresoLayout.setVerticalGroup(
            pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlingresoLayout.createSequentialGroup()
                .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblcod))
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblced, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(lblape, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(pnlingresoLayout.createSequentialGroup()
                        .addComponent(lblcelular, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbnmasculino)
                            .addComponent(rbnfemenino)
                            .addComponent(lblsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addComponent(lbled, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnguardar)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbnfemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnfemeninoActionPerformed
        validar();
    }//GEN-LAST:event_rbnfemeninoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        ObjectContainer base = Db4o.openFile(INICIO.direccion);

        crearAgente(base);
        base.close();

    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped

        char letra = evt.getKeyChar();
        if (!Character.isDigit(letra)) {
            evt.consume();

        }

        if (txtcedula.getText().trim().length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtcedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyReleased
        validar();
    }//GEN-LAST:event_txtcedulaKeyReleased

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char letra = evt.getKeyChar();
        if (Character.isDigit(letra)) {
            evt.consume();
        }

        if (txtnombre.getText().trim().length() > 19) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        validar();
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped

        char letra = evt.getKeyChar();
        if (Character.isDigit(letra)) {
            evt.consume();
        }

        if (txtapellido.getText().trim().length() > 19) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased

        validar();
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void txttelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyReleased
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyReleased

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:

        char letra = evt.getKeyChar();
        if (!Character.isDigit(letra)) {
            evt.consume();
        }

        if (txttelefono.getText().trim().length() > 9) {
            while (!txttelefono.getText().trim().matches("^[0-9]{10}+")) {
                lblcelular.setText("Ingrese un telefono valida");
            }
            evt.consume();
        }

    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        if (txtcorreo.getText().trim().length() > 24) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcorreoKeyTyped

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        validar();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void rbnmasculinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbnmasculinoKeyReleased
    }//GEN-LAST:event_rbnmasculinoKeyReleased

    private void rbnfemeninoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbnfemeninoKeyReleased


    }//GEN-LAST:event_rbnfemeninoKeyReleased

    private void rbnmasculinoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbnmasculinoStateChanged
        validar();
    }//GEN-LAST:event_rbnmasculinoStateChanged

    private void rbnfemeninoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbnfemeninoStateChanged
        validar();
    }//GEN-LAST:event_rbnfemeninoStateChanged

    private void rbnmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnmasculinoActionPerformed
        validar();
    }//GEN-LAST:event_rbnmasculinoActionPerformed

    private void rbnmasculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbnmasculinoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnmasculinoItemStateChanged

    public void crearAgente(ObjectContainer Base) {
        try {
            int aux = 1 + Reporte_agentes.listaagentes.size();
            String auxn = String.valueOf(aux);
            String cod = "00" + auxn;
            


            if (rbnmasculino.isSelected()) {
                sexo = "Masculino";
            } else if (rbnfemenino.isSelected()) {
                sexo = "Femenino";
            }

            Date Seleccion = jDateChooser1.getDate();


            validar();

            // Verificar si ya existe un agente con la misma cédula
            ObjectSet<Agente_inmobiliario> resul = Base.queryByExample(new Agente_inmobiliario(null,null, null,txtcedula.getText().trim(), null, null, null, null, null, null));

            if (!resul.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ya existe un agente con la cédula ingresada.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //String codigo_agente, String usuario, String password, String cedula, String nombre, String apellido, String email, String telefono, String genero, Date fecha_nac
            Agente_inmobiliario agente1 = new Agente_inmobiliario(cod.trim(),null, null, txtcedula.getText().trim(), txtnombre.getText().trim(), txtapellido.getText().trim(), txtcorreo.getText().trim(), txttelefono.getText(), sexo.trim(), Seleccion);

            // Almacenar el agente en la base de datos
            Base.store(agente1);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(this, "Cuenta de agente creada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } finally {
            Base.close();
        }

        // Limpiar los campos después de la creación de la cuenta
        txtcorreo.setText(" ".trim());
        txtcedula.setText(" ".trim());
        lblcod.setText(" ".trim());
        txtnombre.setText(" ".trim());
        txttelefono.setText(" ".trim());
        txtapellido.setText("".trim());
        jDateChooser1.setDate(null);

        rbnfemenino.setSelected(false);
        rbnmasculino.setSelected(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblape;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblced;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcelular;
    private javax.swing.JLabel lblcod;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbled;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblgenero;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JPanel pnlingreso;
    private javax.swing.JRadioButton rbnfemenino;
    private javax.swing.JRadioButton rbnmasculino;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
