
import clases.Cliente;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
        inhabiltarDatos();
        Agrupar();
        Agrupar1();

//        jSpinner1.setModel(new SpinnerNumberModel(0, 0, 60, 1));
//
      
//        rbtSi.addItemListener(item);
//        rbtNo.addItemListener(item);
//        // btnguardar.setEnabled(false);
    }

    public void Agrupar() {
        ButtonGroup botones = new ButtonGroup();
        botones.add(rbmasculinoCli);
        botones.add(rbfemeninoCli);

    }

    public void Agrupar1() {

        ButtonGroup botones1 = new ButtonGroup();
        botones1.add(rbtNo);
        botones1.add(rbtSi);
    }

    String sexo = " ";
    String discapacidad1 = " ";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        Discapacidad = new javax.swing.ButtonGroup();
        txttelefonoCli = new javax.swing.JTextField();
        txtemailCli = new javax.swing.JTextField();
        txtapellidoCli = new javax.swing.JTextField();
        txtnombreCli = new javax.swing.JTextField();
        txtcedulaClie = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblced = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtSi = new javax.swing.JRadioButton();
        rbtNo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtcodigoCli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbmasculinoCli = new javax.swing.JRadioButton();
        rbfemeninoCli = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Datefechaclie = new com.toedter.calendar.JDateChooser();
        txtcontraseña = new javax.swing.JPasswordField();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblDiscapacidad = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttelefonoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoCliActionPerformed(evt);
            }
        });
        getContentPane().add(txttelefonoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 212, 180, -1));
        getContentPane().add(txtemailCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 182, 180, -1));
        getContentPane().add(txtapellidoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 152, 180, -1));
        getContentPane().add(txtnombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 122, 180, -1));
        getContentPane().add(txtcedulaClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 92, 180, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 40, -1));

        lblced.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblced.setText("Cedula:");
        jPanel1.add(lblced, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        genero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        genero.setText("Genero:");
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Discapacidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        rbtSi.setText("Si");
        rbtSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSiActionPerformed(evt);
            }
        });
        jPanel1.add(rbtSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        rbtNo.setText("No");
        rbtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Codigo _ Cliente:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 130, 20));
        jPanel1.add(txtcodigoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 150, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Telefono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 40));

        rbmasculinoCli.setText("Masculino");
        rbmasculinoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmasculinoCliActionPerformed(evt);
            }
        });
        jPanel1.add(rbmasculinoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        rbfemeninoCli.setText("Femenino");
        rbfemeninoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemeninoCliActionPerformed(evt);
            }
        });
        jPanel1.add(rbfemeninoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Contraseña:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 90, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));
        jPanel1.add(Datefechaclie, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 150, -1));

        txtcontraseña.setText("jPasswordField1");
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 160, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGOS DE KAME HOUSE.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 250, 170));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("REGISTRAR CLIENTE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton3.setText("Cargar Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO CLIENTE", "CEDULA", "NOMBRE", "APELLIDO", "EMAIL", "TELEFONO", "EDAD", "GENERO", "DISCAPACIDAD", "FECHA DE NACIMIENTO", "CONTRASEÑA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 810, 210));
        jPanel1.add(lblDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 90, 10));
        jPanel1.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 310, 110, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefonoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoCliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ObjectContainer base = Db4o.openFile(INICIO.direccion);

        Query query = base.query();
        query.constrain(Cliente.class);
        query.descend("cedula").constrain(txtcedulaClie.getText().trim());

        ObjectSet<Cliente> result = query.execute();

        String[] columnNames = {"CODIGO", "CEDULA", "NOMBRE", "APELLIDO", "EMAIL", "TELEFONO", "EDAD", "SEXO", "DISCAPACIDAD", "FECHA DE NACIMIENTO", "CONTRASEÑA"};

        Object[][] data = new Object[result.size()][10];

        int i = 0;
        for (Cliente cliente : result) {
            data[i][0] = cliente.getCodigo_cli();
            data[i][1] = cliente.getCedula();
            data[i][2] = cliente.getNombre();
            data[i][3] = cliente.getApellido();
            data[i][4] = cliente.getEmail();
            data[i][5] = cliente.getTelefono();
            data[i][6] = cliente.getGenero();
            data[i][7] = cliente.getDiscapacidad();
            data[i][8] = cliente.getFecha_nac();
            data[i][9] = cliente.getContraseña();

            i++;
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable1.setModel(model);

        int resul = JOptionPane.showConfirmDialog(null, "Deseas eliminar los datos del Cliente", "Confirmacion", JOptionPane.YES_NO_OPTION);

        if (resul == JOptionPane.YES_OPTION) {
            for (Cliente ClienteDB : result) {

                // Eliminar el Cliente de la base de datos db4o
                base.delete(ClienteDB);
                JOptionPane.showMessageDialog(null, "Se estan borrando los datos del Cliente");

            }
        } else if (resul == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Datos del Cliente no eliminados");
        }

        vaciarTabla();

        base.close();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void vaciarTabla() {
        // Obtenemos el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        // Borramos las filas antiguas del modelo de tabla
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LOGIN_CLIENTES cli = new LOGIN_CLIENTES();
        cli.setVisible(true);
        this.dispose();      
         setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ObjectContainer base = Db4o.openFile(INICIO.direccion);

        ActualizarDatos(base);
        base.close();        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ObjectContainer base = Db4o.openFile(INICIO.direccion);

        String nombre = " ", apellido = " ", email = " ", Telefono = " ", sexo1 = " ", discapacidad = " ", contraseña = " ";
        Date fecha = null;
        Query query = base.query();
        query.constrain(Cliente.class);
        query.descend("cedula").constrain(txtcedulaClie.getText().trim());
        ObjectSet<Cliente> result = query.execute();

        if (!result.isEmpty()) {
            habiltarDatos();
            for (Cliente cliente : result) {
                nombre = cliente.getNombre();
                apellido = cliente.getApellido();
                email = cliente.getEmail();
                Telefono = cliente.getTelefono();
                sexo1 = cliente.getGenero();
                discapacidad = cliente.getDiscapacidad();
                fecha = cliente.getFecha_nac();
                contraseña = cliente.getContraseña();

            }

            txtnombreCli.setText(nombre.trim());
            txtapellidoCli.setText(apellido.trim());
            txtemailCli.setText(email.trim());
            txttelefonoCli.setText(Telefono.trim());
            Datefechaclie.setDate(fecha);
            txtcontraseña.setText(contraseña.trim());

            if (sexo1.equalsIgnoreCase("Masculino")) {
                rbmasculinoCli.setSelected(true);
            } else if (sexo1.equalsIgnoreCase("Femenino")) {
                rbfemeninoCli.setSelected(true);
            }

            if (discapacidad.equalsIgnoreCase("Si")) {
                rbtSi.setSelected(true);
            } else if (discapacidad.equalsIgnoreCase("No")) {
                rbtNo.setSelected(true);
            }
        } else {

            JOptionPane.showMessageDialog(null, "No se encontró ningún Cliente con la cedula ingresada");

        }

        base.close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        ObjectContainer base = Db4o.openFile(INICIO.direccion);

        Query query = base.query();
        query.constrain(Cliente.class);
        query.descend("cedula").constrain(txtcedulaClie.getText().trim());

        ObjectSet<Cliente> result = query.execute();

        String[] columnNames = {"CODIGO", "CEDULA", "NOMBRE", "APELLIDO", "EMAIL", "TELEFONO", "SEXO", "DISCAPACIDAD", "FECHA DE NACIMIENTO", "CONTRASEÑA"};

        Object[][] data = new Object[result.size()][10];

        int i = 0;
        for (Cliente cliente : result) {
            data[i][0] = cliente.getCodigo_cli();
            data[i][1] = cliente.getCedula();
            data[i][2] = cliente.getNombre();
            data[i][3] = cliente.getApellido();
            data[i][4] = cliente.getEmail();
            data[i][5] = cliente.getTelefono();
            data[i][6] = cliente.getGenero();
            data[i][7] = cliente.getDiscapacidad();
            data[i][8] = cliente.getFecha_nac();
            data[i][9] = cliente.getContraseña();

            i++;
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable1.setModel(model);

        base.close();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNoActionPerformed
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNoActionPerformed

    private void rbmasculinoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmasculinoCliActionPerformed
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_rbmasculinoCliActionPerformed

    private void rbfemeninoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemeninoCliActionPerformed
        validar();// TODO add your handling code here:
    }//GEN-LAST:event_rbfemeninoCliActionPerformed

    private void rbtSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSiActionPerformed
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_rbtSiActionPerformed

    public void habiltarDatos() {

        txtnombreCli.setEnabled(true);
        txtapellidoCli.setEnabled(true);
        txtemailCli.setEnabled(true);
        txttelefonoCli.setEnabled(true);
        rbmasculinoCli.setEnabled(true);
        rbfemeninoCli.setEnabled(true);
        rbtSi.setEnabled(true);
        rbtNo.setEnabled(true);
        Datefechaclie.setEnabled(true);
        txtcontraseña.setEnabled(true);

    }

    public void ActualizarDatos(ObjectContainer base) {

        if (rbmasculinoCli.isSelected()) {

            sexo = "Masculino";

        } else if (rbfemeninoCli.isSelected()) {
            sexo = "Femenino";
        }
        if (rbtSi.isSelected()) {

            discapacidad1 = "Si";

        } else if (rbtNo.isSelected()) {
            discapacidad1 = "No";
        }

        // String discapacidad, String contraseña, String cedula, String nombre, String apellido, String email, String telefono, String genero, Date fecha_nac
        Cliente micliente = new Cliente(null, null, txtcedulaClie.getText().trim(), null, null, null, null, null,null);

        ObjectSet res = base.get(micliente);
        Cliente micliente1 = (Cliente) res.next();
        micliente1.setNombre(txtnombreCli.getText().trim());
        micliente1.setApellido(txtapellidoCli.getText().trim());
        micliente1.setEmail(txtemailCli.getText().trim());
        micliente1.setTelefono(txttelefonoCli.getText().trim());
        micliente1.setGenero(sexo.trim());
        micliente1.setDiscapacidad(discapacidad1.trim());
        micliente1.setFecha_nac(Datefechaclie.getDate());
        micliente1.setContraseña(txtcontraseña.getText().trim());

        base.set(micliente1);

        JOptionPane.showMessageDialog(this, "Modificacion exitosa");

        txtcedulaClie.setText(" ");
        txtnombreCli.setText(" ");
        txtapellidoCli.setText(" ");
        txtemailCli.setText(" ");
        txttelefonoCli.setText("");
        Datefechaclie.setDate(null);

        rbmasculinoCli.setSelected(false);
        rbfemeninoCli.setSelected(false);

        rbtSi.setSelected(false);
        rbtNo.setSelected(false);

        txtcontraseña.setText(" ");

        inhabiltarDatos();

    }

    public void inhabiltarDatos() {

        txtnombreCli.setEnabled(false);
        txtapellidoCli.setEnabled(false);
        txtemailCli.setEnabled(false);
        txttelefonoCli.setEnabled(false);
        txtcontraseña.setEnabled(false);
        rbtSi.setEnabled(false);
        rbtNo.setEnabled(false);
        Datefechaclie.setEnabled(false);
        rbmasculinoCli.setEnabled(false);
        rbfemeninoCli.setEnabled(false);
    }

    public void validar() {

        if (!rbfemeninoCli.isSelected() || !rbmasculinoCli.isSelected()) {
            lblGenero.setText("Campo requerido");

        } else {
            lblGenero.setText(" ");
        }

        if (!rbtSi.isSelected() || !rbtNo.isSelected()) {
            lblDiscapacidad.setText("Campo requerido");

        } else {
            lblDiscapacidad.setText(" ");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Datefechaclie;
    private javax.swing.ButtonGroup Discapacidad;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiscapacidad;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblced;
    private javax.swing.JRadioButton rbfemeninoCli;
    private javax.swing.JRadioButton rbmasculinoCli;
    private javax.swing.JRadioButton rbtNo;
    private javax.swing.JRadioButton rbtSi;
    private javax.swing.JTextField txtapellidoCli;
    private javax.swing.JTextField txtcedulaClie;
    private javax.swing.JTextField txtcodigoCli;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtemailCli;
    private javax.swing.JTextField txtnombreCli;
    private javax.swing.JTextField txttelefonoCli;
    // End of variables declaration//GEN-END:variables
}
